# Generated by Django 5.1.15 on 2026-09-05 09:18

import apps.business.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Business Name')),
                ('category', models.CharField(max_length=100, verbose_name='Business Category')),
                ('category_other', models.CharField(blank=True, max_length=100, null=True, verbose_name='Other Category')),
                ('location', models.CharField(max_length=255, verbose_name='Business Location')),
                ('description', models.TextField(help_text='What does your business do? Describe it in 1-2 sentences.', verbose_name='Business Description')),
                ('products_services', models.JSONField(default=list, verbose_name='Products or Services Offered')),
                ('main_specialty_products', models.JSONField(default=list, verbose_name='Main / Specialty Products or Services')),
                ('brand_tone', models.JSONField(default=list, verbose_name='Brand Tone/Sound')),
                ('communication_length', models.CharField(max_length=50, verbose_name='Communication Length')),
                ('communication_style', models.CharField(max_length=50, verbose_name='Writing Style')),
                ('preferred_languages', models.JSONField(default=list, verbose_name='Preferred Languages')),
                ('preferred_language_other', models.CharField(blank=True, max_length=100, null=True, verbose_name='Other Language')),
                ('differentiator', models.TextField(help_text='What are you known for? What makes you different from other businesses?', verbose_name='What Makes Business Different')),
                ('important_facts', models.TextField(help_text='What important factual information should the AI know about your business?', verbose_name='Important Business Facts')),
                ('default_ai_rules', models.JSONField(default=apps.business.models.default_ai_restrictions, verbose_name='Default AI Restrictions')),
                ('custom_restrictions', models.TextField(blank=True, help_text='Anything the AI should never claim, assume, mention, or promise?', null=True, verbose_name='Additional Restrictions')),
                ('google_review_url', models.URLField(max_length=500, verbose_name='Google Review URL')),
                ('website', models.URLField(blank=True, max_length=500, null=True, verbose_name='Website URL')),
                ('opening_hours', models.TextField(blank=True, null=True, verbose_name='Opening Hours')),
                ('target_customers', models.JSONField(blank=True, default=list, verbose_name='Target Customers')),
                ('faqs', models.JSONField(blank=True, default=list, verbose_name='Frequently Asked Questions')),
                ('business_story', models.TextField(blank=True, null=True, verbose_name='Business Story')),
                ('important_terminology', models.TextField(blank=True, null=True, verbose_name='Important Terminology')),
                ('is_configured', models.BooleanField(default=False, verbose_name='Configuration Completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
