# Generated by Django 5.1.15 on 2026-09-05 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI (GPT-4o / GPT-4o-mini)'), ('gemini', 'Google Gemini (Gemini 1.5 Flash / Pro)'), ('groq', 'Groq (Llama 3.1 / Mixtral)'), ('anthropic', 'Anthropic (Claude 3.5 Haiku / Sonnet)')], default='openai', max_length=50, verbose_name='AI Provider')),
                ('api_key', models.CharField(max_length=500, verbose_name='API Key')),
                ('model_name', models.CharField(default='gpt-4o-mini', max_length=100, verbose_name='Model Designation')),
                ('is_active', models.BooleanField(default=False, verbose_name='Key Verified & Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_config', to='business.businessprofile')),
            ],
        ),
    ]
