# Generated by Django 5.1.15 on 2026-09-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_aiconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='total_ai_generated',
            field=models.PositiveIntegerField(default=0, verbose_name='Total AI Reviews Generated'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='total_copies_redirects',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Copies & Redirects'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='total_views',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Customer Views'),
        ),
    ]
