# Generated by Django 5.1.15 on 2026-09-05 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_businessprofile_total_ai_generated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfig',
            name='model_name',
            field=models.CharField(default='gemini-2.5-flash', max_length=100, verbose_name='Model Designation'),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI (GPT-4o / GPT-4o-mini)'), ('gemini', 'Google Gemini (Gemini 2.5 Flash / Pro)'), ('groq', 'Groq (Llama 3.1 / Mixtral)'), ('anthropic', 'Anthropic (Claude 3.5 Haiku / Sonnet)')], default='gemini', max_length=50, verbose_name='AI Provider'),
        ),
        migrations.CreateModel(
            name='AIKeyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI (GPT-4o / GPT-4o-mini)'), ('gemini', 'Google Gemini (Gemini 2.5 Flash / Pro)'), ('groq', 'Groq (Llama 3.1 / Mixtral)'), ('anthropic', 'Anthropic (Claude 3.5 Haiku / Sonnet)')], max_length=50, verbose_name='Provider')),
                ('encrypted_api_key', models.CharField(max_length=500, verbose_name='Encrypted Key Payload')),
                ('masked_key', models.CharField(max_length=100, verbose_name='Masked Key Preview')),
                ('model_name', models.CharField(default='gemini-2.5-flash', max_length=100, verbose_name='Model Name')),
                ('status', models.CharField(choices=[('active', 'Active Key'), ('archived', 'Archived History'), ('revoked', 'Revoked / Compromised')], default='active', max_length=20, verbose_name='Key Status')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Audit Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_history', to='business.businessprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
