# Generated by Django 5.1.15 on 2026-09-10 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_aiconfig_model_name_alter_aiconfig_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enjoyed_options', models.JSONField(blank=True, default=list, verbose_name='Enjoyed Options')),
                ('item_used', models.CharField(blank=True, max_length=255, verbose_name='Item or Service Used')),
                ('feedback_text', models.TextField(verbose_name='Complaint / Feedback Details')),
                ('contact_info', models.CharField(blank=True, max_length=255, verbose_name='Customer Contact (Email or Phone)')),
                ('status', models.CharField(choices=[('new', 'New Complaint'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='new', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_feedbacks', to='business.businessprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
